//正确答案
//var answers = new Array("common","results","consequently","basis","detection","monitor","symbols","average","dramatically","symptoms");
//选项
//var options = new Array("common","results","consequently","basis","detection","monitor","symbols","average","dramatically","symptoms","reason","distributed","including","developing","shared");
var analysis = [
	{
		"answer":"第一题答案",
		"structure":"第一题解析."
	},
	{
		"answer":"第二题答案",
		"structure":"第二题解析"
	},
	{
		"answer":"第三题答案",
		"structure":"第三题解析"
	},
	{
		"answer":"第四题答案",
		"structure":"第四题解析"
	},
	{
		"answer":"第五题答案",
		"structure":"第五题解析"
	},
	{
		"answer":"第六题答案",
		"structure":"第六题解析"
	},
	{
		"answer":"第七题答案",
		"structure":"第七题解析"
	},
	{
		"answer":"第八题答案",
		"structure":"第八题解析"
	},
	{
		"answer":"第九题答案",
		"structure":"第九题解析"
	},
	{
		"answer":"第十题答案",
		"structure":"第十题解析"
	},
];
